version: '3'

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    volumes:
    - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
 

  mariadb:
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/macote/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/macote/data/mariadb'
